#!/bin/bash

 # Color directory
CD="$HOME/.Xresources"

# Fetch the Colors
BG=$(cat ${CD} | grep -i background | tail -c 8)
FG=$(cat ${CD} | grep -i foreground | tail -c 8)

BLACK=$(cat ${CD} | grep -i color8 | tail -c 8)
RED=$(cat ${CD} | grep -i color9 | tail -c 8)
GREEN=$(cat ${CD} | grep -i color10 | tail -c 8)
YELLOW=$(cat ${CD} | grep -i color11 | tail -c 8)
BLUE=$(cat ${CD} | grep -i color12 | tail -c 8)
MAGENTA=$(cat ${CD} | grep -i color13 | tail -c 8)
CYAN=$(cat ${CD} | grep -i color14 | tail -c 8)
WHITE=$(cat ${CD} | grep -i color15 | tail -c 8)

# Fonts
FONT1="-misc-fixed-medium-r-normal--10-70-*-*-*-*-*-*"
FONT2="-lucy-tewi-medium-r-normal--11-*-*-*-*-*-*-*"
FONT3="-xos4-terminus-bold-r-normal--12-120-72-72-c-60-iso10646-1"
FONT4="-*-cure-medium-*-*-*-*-*-*-*-*"

TMUS="mpc toggle"
NMUS="mpc next"
VOLU="mpc volume + 5"
VOLD="mpc volume - 5"

# Functions

#Workspace number

 ws(){
	ws=$(i3-msg -t get_outputs | sed 's/.*"current_workspace":"\([^"]*\)".*/\1/')
	echo "%{F$RED}${ws}"
}

music() {
    music=$(n=$(mpc current); if [ -z "$n" ] ; then echo; else echo "$n"; fi)
	echo "%{F$GREEN}${music}"
}
	
 clock(){
  clock=$(date "+%d %b %Y  %H:%M")
	echo "%{F$RED}${clock}"
}

 vol(){
  vol=$(amixer get 'Master' | grep Mono: | sed 's/ *Mono: .* \[\([^ ]*\)\] \[[^ ]*\] \[\([^ ]*\)\]/\1 \2/;s/.*off/off/;s/\([^ ]*\).*/\1/')
	echo "%{F$YELLOW} ${vol}"
}

while :; do 	
	echo "   $(ws)  %{A1:$TMUS:}%{A3:$NMUS:}$(music)%{A}%{A}%{c}%{r} %{A}%{A}%{A} $(clock)  %{A} "
	 sleep .5
done | lemonbar -g x18+0+0 -f "$FONT4"  -B "$BG" -F "$FG" -p -d  | \
    while :; do read line; eval $line; done &
